-- -- ARITHEMETIC OPerator(+,-,*,/)


-- SELECT 10+5 AS ADDITION FROM DUAL;
-- SELECT 10-5 AS SUBTRACTTION FROM DUAL;
-- SELECT 10*5 AS MULTITION FROM DUAL;
-- SELECT 10/5 AS DIVISION FROM DUAL

-- COMPARISION OPERATORS (<,><=,>=,=,<>)

-- SELECT *FROM HR.EMPLOYEES
-- SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY<15000
-- SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY>15000
-- SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY<=15000
-- SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY>=15000
-- SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY=17000
-- SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY<>17000


-- LOGICAL OPERATORS (and,or,not)


-- SELECT *FROM    HR.EMPLOYEES 

-- SELECT * FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=100 AND SALARY=24000
-- SELECT * FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=100 OR EMPLOYEE_ID=110
-- SELECT * FROM HR.EMPLOYEES WHERE NOT EMPLOYEE_ID=100

-- BETWEEN,IN,LIKE OPERATORS
-- #### BETWEEN OPERATOrs##
-- -- SELECT 10 BETWEEN 5 AND 15  OUTPUT FROM DUAL
-- -- SELECT 100 BETWEEN 5 AND 15  OUTPUT FROM DUAL
-- -- SELECT * BETWEEN 5 AND 15  OUTPUT FROM DUAl

-- ###in oper##
-- select * from hr.employees where employee_id in (110,120,102)

-- ## like operator##
-- select * from hr.employees where first_name like '%e'
-- select * from hr.employees where first_name like 'e%'
-- select * from hr.employees where first_name like '_____'