-- SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, RANK() OVER (ORDER BY SALARY) FROM HR.EMPLOYEES
-- SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, DENSE_RANK() OVER (ORDER BY SALARY) FROM HR.EMPLOYEES
-- SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, ROW_NUMBER() OVER (ORDER BY SALARY) FROM HR.EMPLOYEES
-- SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, LAG(SALARY) OVER (ORDER BY SALARY) FROM HR.EMPLOYEES
 



--   INLINE QUERIES(DERIVRED TABLES)CREATE A SUB TABLE FOR FILTERING
-- SELECT EMPLOYEE_ID,SALARY

-- FROM( SELECT EMPLOYEE_ID,SALARY WHERE SALARY>5000)