-- 1.count the number of employees in each department
-- select department_id,count(*) from hr.employees group by department_id

-- 2.find the average the salary in each department
-- select department_id,avg(salary) from hr.employees group by department_id

-- 3.find the maximum and minimum salry in each department
-- select department_id,max(salary),min(salary) from hr.employees group by department_id

-- 4.find the total salary paid in each department
-- select department_id,sum(salary) from hr.employees group by department_id


-- 5.count the number of employees in each job role
-- select job_id,count(*) from hr.employees group by job_id

-- 6.find the avg salary in each job role
-- select job_id,avg(salary) from hr.employees group by job_id

-- 7.find the maximum salary for rach job role
-- select job_id,max(salary) as max_salary from hr.employees group by job_id

-- 8.find the mimimum salary for each job role
-- select job_id,min(salary) as min_salary from hr.employees group by job_id

-- 9.find the total salary for each job roles
-- select job_id,sum(salary) as total_salary from hr.employees group by job_id

-- 10.count the no.of employees hired in each year
-- select extract(year from hire_date) as hired_year,count(*) as total_employees 
-- from hr.employees 
-- group by extract(year from hire_date)
-- order by hired_year

-- 11.find tne total salry paid in each location
-- select d.location_id,sum(e.salary) as total_salary
-- from hr.employees e
-- join hr.departments d on e.department_id=d.DEPARTMENT_ID
-- group by d.location_id

-- 12.find the no.of employees in each managers team
-- select * from hr.employees
-- select manager_id,count(*) as team_size
-- from hr.EMPLOYEES
-- where manager_id is not NULL
-- group by manager_id

-- `13.find the highest salary in each manager team
-- select manager_id,max(salary) as highest_salary 
-- from hr.employees
-- where manager_id is not null
-- group by manager_id

-- 14.find the average salary in each team
-- select manager_id,avg(salary) as avg_salary 
-- from hr.employees
-- where manager_id is not null
-- group by manager_id

-- 15.count the no.of employees hired in each month of the year
-- select extract(month from hire_date) as hire_month,count(*)
-- from hr.EMPLOYEES
-- group by extract(month from hire_date)
-- order by hire_month


-- 16.find the department with the highest total salary
-- select department_id,sum(salary) as total_salry
-- from hr.EMPLOYEES
-- group by DEPARTMENT_ID
-- order by total_salry DESC
-- fetch first 1 row only


-- 17.find the job role with highest avg salary
-- select job_id,avg(salary) as avg_salary
-- from hr.EMPLOYEES
-- group by JOB_ID
-- order by avg_salary DESC
-- fetch first 1 row only

-- 18.find the number of employees in each city
-- ## we are fetching no.of employees for each city we need emplyee_id(hr.employees),city(hr.locations)
-- ## employees,departments --> .department_id
-- ## departments,locations--->location_id

-- select * from hr.locations
-- select l.city,count(*) as total_employees
-- from hr.employees e
-- join hr.departments d on e.department_id=d.DEPARTMENT_ID
-- join hr.locations l on d.location_id=l.LOCATION_ID
-- group by l.city

-- 19.find the no.of employees who have a commision,grouped by department
-- select * from hr.employees
-- select department_id,count(*) as total_employees
-- from hr.EMPLOYEES
-- where commission_pct is not NULL
-- group by department_id

-- 20.find the sum of salaries for employees who have a commission, grouped by department
-- select department_id,sum(salary) as total_salary
-- from hr.EMPLOYEES
-- where commission_pct is not NULL
-- group by department_id


-- ##### assignment questions  ######

-- 1.find tne total no of. sales in each rptoduct
-- select * from sh.sales
-- select prod_id,count(*) as total_sales
-- from sh.SALES
-- group by prod_id

-- 2.find the average sale amount for each product
-- select prod_id,avg(amount_sold) 
-- from sh.SALES
-- group by prod_id

-- 3.find the max and min sale amount in each product
-- select prod_id,max(amount_sold),min(amount_sold)
-- from sh.SALES
-- group by PROD_ID

-- -- 4.find the total revenue generated by each product
-- select * from sh.SALES
-- select prod_id,sum(amount_sold) as total_revenue
-- from sh.sales
-- group by PROD_Id
-- order by total_revenue desc

-- 5.count the number of sales transactions for each customer
-- select cust_id,count(*) as total_sales
--  from sh.CUSTOMERS
-- group by CUST_ID

-- 6.find the avg sale amount per customer
-- select cust_id,avg(amount_sold)
-- from sh.sales
-- group by cust_id

-- 7.find the highest purchase amount for each customer
-- select cust_id,max(amount_sold)
-- from sh.sales
-- group by cust_id

-- 8.find the lowest purchase amount for each customer
-- select cust_id,min(amount_sold)
-- from sh.sales
-- group by cust_id

-- 9.find the total revenue generated by each store location
-- sales(cust_id) --> sales,customers(cust_id)-->country_id(location)

-- select * from sh.countries
-- select c.country_id,sum(amount_sold) as total_revenue
-- from sh.sales s
-- join sh.customers c on c.cust_id=s.CUST_ID
-- group by country_id



-- 10.count the no.os sales for each region
-- sales(cust_id)-->sales,customers(cust_id,country_id),countries(country_id)-->country_region
-- select cr.country_region ,count(*) as  total_sales
-- from sh.sales s
-- join sh.customers c on c.cust_id=s.CUST_ID
-- join sh.countries cr on cr.country_id=c.COUNTRY_ID
-- group by country_region
 
--  11.find the total revenue for each region
-- select cr.country_region,sum(amount_sold) as total_revenue
-- from sh.sales s
-- join sh.customers c on c.cust_id=s.CUST_ID
-- join sh.countries cr on cr.country_id=c.country_id
-- group by country_region

--  12.find the total revenue for each region
-- select cr.country_region,avg(amount_sold) as avg_revenue
-- from sh.sales s
-- join sh.customers c on c.cust_id=s.CUST_ID
-- join sh.countries cr on cr.country_id=c.country_id
-- group by country_region

-- 13.count the no. of sales per month
-- select * from sh.sales
-- select extract(month from time_id) as month,count(*) as total_sales
-- from sh.SALES
-- group by month
-- order by month desc

-- 14.total revenue  per month
-- select * from sh.sales
-- select extract(month from time_id) as month,sum(amount_sold) as total_revenue
-- from sh.SALES
-- group by month
-- order by month desc

-- 15.find the product that generated highest revenue
-- select prod_id,sum(amount_sold) as highest_revenue
-- from sh.sales
-- group by PROD_ID
-- order by highest_revenue DESC
-- fetch first 1 row only

select * from sh.products


